# Generated by Django 4.2.10 on 2024-02-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Company name"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company address",
                    ),
                ),
                (
                    "phone_number1",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone number 1",
                    ),
                ),
                (
                    "phone_number2",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone number 2",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Account number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=300,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=300, null=True, verbose_name="email"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Merchandise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="news/videos/"),
                ),
                ("photo1", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo2", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo3", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo4", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo5", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo6", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo7", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo8", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo9", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo10", models.ImageField(blank=True, upload_to="news/photos/")),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=20, verbose_name="Time")),
                (
                    "monday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Monday",
                    ),
                ),
                (
                    "tuesday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Tuesday",
                    ),
                ),
                (
                    "wednesday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Wednesday",
                    ),
                ),
                (
                    "thursday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Thursday",
                    ),
                ),
                (
                    "friday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Friday",
                    ),
                ),
                (
                    "saturday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Saturday",
                    ),
                ),
            ],
            options={"verbose_name": "Shedule", "verbose_name_plural": "Shedules",},
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="trainers/")),
                ("description", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("parent_name", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("advanced", "Advanced"),
                            ("beginner", "Beginner"),
                            ("child", "Child"),
                            ("basic-course", "Basic Course"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchandisePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="merchandise/")),
                (
                    "merchandise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.merchandise",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="merchandise",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="merchandise_photos",
                to="backend.merchandisephoto",
            ),
        ),
        migrations.AddField(
            model_name="merchandise",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="backend.size"),
        ),
    ]
