# Generated by Django 4.2.10 on 2024-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_remove_post_photo1_remove_post_photo10_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="photo",),
        migrations.AddField(
            model_name="post",
            name="photo1",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo10",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo2",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo3",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo4",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo5",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo6",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo7",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo8",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="photo9",
            field=models.FileField(blank=True, upload_to="news/photos/"),
        ),
    ]
