# Generated by Django 4.2.10 on 2024-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_category_merchandise_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="merchandise", name="photos",),
        migrations.AddField(
            model_name="merchandise",
            name="photo1",
            field=models.FileField(blank=True, upload_to="merchandise/"),
        ),
        migrations.AddField(
            model_name="merchandise",
            name="photo2",
            field=models.FileField(blank=True, upload_to="merchandise/"),
        ),
        migrations.AddField(
            model_name="merchandise",
            name="photo3",
            field=models.FileField(blank=True, upload_to="merchandise/"),
        ),
        migrations.DeleteModel(name="MerchandisePhoto",),
    ]
